# Book Recommendation system

Dataset url: http://www2.informatik.uni-freiburg.de/~cziegler/BX/

## Read the dataset with the necessary features

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
books = pd.read_csv('BX-Books.csv', sep=';', error_bad_lines=False, encoding="latin-1")
books.columns = ['ISBN', 'bookTitle', 'bookAuthor', 'yearOfPublication', 'publisher', 'imageUrlS', 'imageUrlM', 'imageUrlL']
users =  pd.read_csv('BX-Users.csv', sep=';', error_bad_lines=False, encoding="latin-1")
users.columns = ['userID', 'Location', 'Age']
ratings = pd.read_csv('BX-Book-Ratings.csv', sep=';', error_bad_lines=False, encoding="latin-1")
ratings.columns = ['userID', 'ISBN', 'bookRating']

b'Skipping line 6451: expected 8 fields, saw 9\nSkipping line 43666: expected 8 fields, saw 10\nSkipping line 51750: expected 8 fields, saw 9\n'
b'Skipping line 92037: expected 8 fields, saw 9\nSkipping line 104318: expected 8 fields, saw 9\nSkipping line 121767: expected 8 fields, saw 9\n'
b'Skipping line 144057: expected 8 fields, saw 9\nSkipping line 150788: expected 8 fields, saw 9\nSkipping line 157127: expected 8 fields, saw 9\nSkipping line 180188: expected 8 fields, saw 9\nSkipping line 185737: expected 8 fields, saw 9\n'
b'Skipping line 209387: expected 8 fields, saw 9\nSkipping line 220625: expected 8 fields, saw 9\nSkipping line 227932: expected 8 fields, saw 11\nSkipping line 228956: expected 8 fields, saw 10\nSkipping line 245932: expected 8 fields, saw 9\nSkipping line 251295: expected 8 fields, saw 9\nSkipping line 259940: expected 8 fields, saw 9\nSkipping line 261528: expected 8 fields, saw 9\n'
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:27

In [ ]:
books.head(1)

ISBN  ...                                          imageUrlL
0  0002005018  ...  http://images.amazon.com/images/P/0002005018.0...

[1 rows x 8 columns]

In [ ]:
users.head(1)

userID                   Location Age
0       2  stockton, california, usa  18

In [ ]:
ratings.head(1)

userID        ISBN  bookRating
0  276726  0155061224           5

## Recommendation Based on Rating Counts

In [ ]:
rating_count = pd.DataFrame(ratings.groupby('ISBN')['bookRating'].count())
rating_count.sort_values('bookRating', ascending=False).head()

bookRating
ISBN                  
0971880107        2502
0316666343        1295
0385504209         883
0060928336         732
0312195516         723

In [ ]:
most_rated_books = pd.DataFrame(['0971880107', '0316666343', '0385504209', '0060928336', '0312195516'], index=np.arange(5), columns = ['ISBN'])
most_rated_books_summary = pd.merge(most_rated_books, books, on='ISBN')
most_rated_books_summary

ISBN  ...                                          imageUrlL
0  0971880107  ...  http://images.amazon.com/images/P/0971880107.0...
1  0316666343  ...  http://images.amazon.com/images/P/0316666343.0...
2  0385504209  ...  http://images.amazon.com/images/P/0385504209.0...
3  0060928336  ...  http://images.amazon.com/images/P/0060928336.0...
4  0312195516  ...  http://images.amazon.com/images/P/0312195516.0...

[5 rows x 8 columns]

## Recommendations based on correlations


In [ ]:
average_rating = pd.DataFrame(ratings.groupby('ISBN')['bookRating'].mean())
average_rating['ratingCount'] = pd.DataFrame(ratings.groupby('ISBN')['bookRating'].count())
average_rating.sort_values('ratingCount', ascending=False).head()

bookRating  ratingCount
ISBN                               
0971880107    1.019584         2502
0316666343    4.468726         1295
0385504209    4.652322          883
0060928336    3.448087          732
0312195516    4.334716          723

### To ensure statistical significance, users with less than 200 ratings, and books with less than 100 ratings are excluded.

In [ ]:
ratings.shape

(1149779, 3)

In [ ]:
counts1 = ratings['userID'].value_counts()
ratings = ratings[ratings['userID'].isin(counts1[counts1 >= 200].index)]
counts = ratings['bookRating'].value_counts()
ratings = ratings[ratings['bookRating'].isin(counts[counts >= 100].index)]

In [ ]:
ratings.shape

(527556, 3)

In [ ]:
ratings.describe()

userID     bookRating
count  527556.000000  527556.000000
mean   141808.258437       1.976196
std     80639.772119       3.512230
min       254.000000       0.000000
25%     73394.000000       0.000000
50%    144131.000000       0.000000
75%    212898.000000       3.000000
max    278418.000000      10.000000

### Rating matrix


In [ ]:
ratings_pivot = ratings.pivot(index='userID', columns='ISBN').bookRating
userID = ratings_pivot.index
ISBN = ratings_pivot.columns
print(ratings_pivot.shape)
ratings_pivot.head()

(905, 207699)


ISBN     0330299891   0375404120   0586045007  ...  b00005wz75  cn108465  cn113107
userID                                         ...                                
254             NaN          NaN          NaN  ...         NaN       NaN       NaN
2276            NaN          NaN          NaN  ...         NaN       NaN       NaN
2766            NaN          NaN          NaN  ...         NaN       NaN       NaN
2977            NaN          NaN          NaN  ...         NaN       NaN       NaN
3363            NaN          NaN          NaN  ...         NaN       NaN       NaN

[5 rows x 207699 columns]

In [ ]:
books[books['ISBN']=='0316666343']

ISBN  ...                                          imageUrlL
407  0316666343  ...  http://images.amazon.com/images/P/0316666343.0...

[1 rows x 8 columns]

In [ ]:
bones_ratings = ratings_pivot['0316666343']
similar_to_bones = ratings_pivot.corrwith(bones_ratings)
corr_bones = pd.DataFrame(similar_to_bones, columns=['pearsonR'])
corr_bones.dropna(inplace=True)
corr_summary = corr_bones.join(average_rating['ratingCount'])
corr_summary[corr_summary['ratingCount']>=300].sort_values('pearsonR', ascending=False).head(10)

/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2526: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2455: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)


pearsonR  ratingCount
ISBN                             
0316666343  1.000000         1295
0312291639  0.471872          354
0316601950  0.434248          568
0446610038  0.429712          391
0446672211  0.421478          585
0385265700  0.351635          319
0345342968  0.316922          321
0060930535  0.309860          494
0375707972  0.308145          354
0684872153  0.272480          326

In [ ]:
books_corr_to_bones = pd.DataFrame(['0312291639', '0316601950', '0446610038', '0446672211', '0385265700', '0345342968', '0060930535', '0375707972', '0684872153'], 
                                  index=np.arange(9), columns=['ISBN'])
corr_books = pd.merge(books_corr_to_bones, books, on='ISBN')
corr_books

ISBN  ...                                          imageUrlL
0  0312291639  ...  http://images.amazon.com/images/P/0312291639.0...
1  0316601950  ...  http://images.amazon.com/images/P/0316601950.0...
2  0446610038  ...  http://images.amazon.com/images/P/0446610038.0...
3  0446672211  ...  http://images.amazon.com/images/P/0446672211.0...
4  0385265700  ...  http://images.amazon.com/images/P/0385265700.0...
5  0345342968  ...  http://images.amazon.com/images/P/0345342968.0...
6  0060930535  ...  http://images.amazon.com/images/P/0060930535.0...
7  0375707972  ...  http://images.amazon.com/images/P/0375707972.0...
8  0684872153  ...  http://images.amazon.com/images/P/0684872153.0...

[9 rows x 8 columns]

## Collaborative Filtering Using k-Nearest Neighbors (kNN)


In [ ]:
combine_book_rating = pd.merge(ratings, books, on='ISBN')
columns = ['yearOfPublication', 'publisher', 'bookAuthor', 'imageUrlS', 'imageUrlM', 'imageUrlL']
combine_book_rating = combine_book_rating.drop(columns, axis=1)
combine_book_rating.head()

userID  ...                                          bookTitle
0  277427  ...  Politically Correct Bedtime Stories: Modern Ta...
1    3363  ...  Politically Correct Bedtime Stories: Modern Ta...
2   11676  ...  Politically Correct Bedtime Stories: Modern Ta...
3   12538  ...  Politically Correct Bedtime Stories: Modern Ta...
4   13552  ...  Politically Correct Bedtime Stories: Modern Ta...

[5 rows x 4 columns]

In [ ]:
combine_book_rating.shape

(488742, 4)

In [ ]:
combine_book_rating = combine_book_rating.dropna(axis = 0, subset = ['bookTitle'])

book_ratingCount = (combine_book_rating.
     groupby(by = ['bookTitle'])['bookRating'].
     count().
     reset_index().
     rename(columns = {'bookRating': 'bookTotalRatingCount'})
     [['bookTitle', 'bookTotalRatingCount']]
    )
book_ratingCount.head()

bookTitle  bookTotalRatingCount
0   A Light in the Storm: The Civil War Diary of ...                     2
1                              Always Have Popsicles                     1
2               Apple Magic (The Collector's series)                     1
3   Beyond IBM: Leadership Marketing and Finance ...                     1
4   Clifford Visita El Hospital (Clifford El Gran...                     1

In [ ]:
rating_with_totalRatingCount = combine_book_rating.merge(book_ratingCount, left_on = 'bookTitle', right_on = 'bookTitle', how = 'left')
rating_with_totalRatingCount.head()

userID  ... bookTotalRatingCount
0  277427  ...                   82
1    3363  ...                   82
2   11676  ...                   82
3   12538  ...                   82
4   13552  ...                   82

[5 rows x 5 columns]

In [ ]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)
print(book_ratingCount['bookTotalRatingCount'].describe())

count   160576.000
mean         3.044
std          7.428
min          1.000
25%          1.000
50%          1.000
75%          2.000
max        365.000
Name: bookTotalRatingCount, dtype: float64


In [ ]:
print(book_ratingCount['bookTotalRatingCount'].quantile(np.arange(.9, 1, .01)))

0.900    5.000
0.910    6.000
0.920    7.000
0.930    7.000
0.940    8.000
0.950   10.000
0.960   11.000
0.970   14.000
0.980   19.000
0.990   31.000
Name: bookTotalRatingCount, dtype: float64


In [ ]:
rating_with_totalRatingCount.shape

(488742, 5)

In [ ]:
popularity_threshold = 50
rating_popular_book = rating_with_totalRatingCount.query('bookTotalRatingCount >= @popularity_threshold')
rating_popular_book.head()

userID  ... bookTotalRatingCount
0  277427  ...                   82
1    3363  ...                   82
2   11676  ...                   82
3   12538  ...                   82
4   13552  ...                   82

[5 rows x 5 columns]

In [ ]:
rating_popular_book.shape

(62149, 5)

### Filter to users in US and Canada only

In [ ]:
users.shape

(278857, 3)

In [ ]:
rating_popular_book.shape

(62149, 5)

In [ ]:
combined = rating_popular_book.merge(users, left_on = 'userID', right_on = 'userID', how = 'left')
us_canada_user_rating = combined[combined['Location'].str.contains("usa|canada")]
us_canada_user_rating=us_canada_user_rating.drop('Age', axis=1)
us_canada_user_rating.head()

userID        ISBN  ...  bookTotalRatingCount                       Location
0  277427  002542730X  ...                    82          gilbert, arizona, usa
1    3363  002542730X  ...                    82      knoxville, tennessee, usa
3   12538  002542730X  ...                    82          byron, minnesota, usa
4   13552  002542730X  ...                    82        cordova, tennessee, usa
5   16795  002542730X  ...                    82  mechanicsville, maryland, usa

[5 rows x 6 columns]

In [ ]:
us_canada_user_rating.shape

(56396, 6)

### Cosine Similarity

![image.png](https://dataconomy.com/wp-content/uploads/2015/04/Five-most-popular-similarity-measures-implementation-in-python-4.webp)

### Implementing kNN


In [ ]:
from scipy.sparse import csr_matrix
us_canada_user_rating = us_canada_user_rating.drop_duplicates(['userID', 'bookTitle'])
us_canada_user_rating_pivot = us_canada_user_rating.pivot(index = 'bookTitle', columns = 'userID', values = 'bookRating').fillna(0)
us_canada_user_rating_pivot

userID                                              254     ...  278418
bookTitle                                                   ...        
1984                                                 9.000  ...   0.000
1st to Die: A Novel                                  0.000  ...   0.000
2nd Chance                                           0.000  ...   0.000
4 Blondes                                            0.000  ...   0.000
84 Charing Cross Road                                0.000  ...   0.000
...                                                    ...  ...     ...
Year of Wonders                                      0.000  ...   0.000
You Belong To Me                                     0.000  ...   0.000
Zen and the Art of Motorcycle Maintenance: An I...   0.000  ...   0.000
Zoya                                                 0.000  ...   0.000
\O\" Is for Outlaw"                                  0.000  ...   0.000

[746 rows x 734 columns]

In [ ]:
us_canada_user_rating_matrix = csr_matrix(us_canada_user_rating_pivot.values)
us_canada_user_rating_matrix

<746x734 sparse matrix of type '<class 'numpy.float64'>'
	with 13028 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.neighbors import NearestNeighbors


model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model_knn.fit(us_canada_user_rating_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

### Check Prediction bookTitle Chromosome_Book

In [ ]:
Chromosome_Book = us_canada_user_rating_pivot.loc[['Chromosome 6']]
Chromosome_Book

userID        254     2276    2766    2977    ...  275970  277427  277639  278418
bookTitle                                     ...                                
Chromosome 6   0.000   0.000   0.000   0.000  ...   0.000   0.000   0.000   0.000

[1 rows x 734 columns]

In [ ]:
distances, indices = model_knn.kneighbors(Chromosome_Book.values.reshape(1, -1), n_neighbors = 6)

In [ ]:
distances

array([[2.22044605e-16, 3.63639858e-01, 6.82911738e-01, 6.92616434e-01,
        7.12197510e-01, 7.30848054e-01]])

In [ ]:
indices

array([[116,  36, 592, 702, 128, 283]])

In [ ]:
for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format('Chromosome 6'))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, us_canada_user_rating_pivot.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendations for Chromosome 6:

1: Acceptable Risk, with distance of 0.3636398583669789:
2: The Killing Game: Only One Can Win...and the Loser Dies, with distance of 0.6829117384505824:
3: Vector, with distance of 0.6926164340829276:
4: Contagion, with distance of 0.7121975101304703:
5: Invasion, with distance of 0.7308480536731475:


### Predict All raw

In [ ]:
distances, indices = model_knn.kneighbors(us_canada_user_rating_pivot, n_neighbors = 6)

In [ ]:
distances

array([[2.22044605e-16, 7.09060224e-01, 7.18762275e-01, 7.36707118e-01,
        7.50157940e-01, 7.54097833e-01],
       [1.11022302e-16, 7.26644021e-01, 7.30085037e-01, 7.34410040e-01,
        7.41409240e-01, 7.42915807e-01],
       [2.22044605e-16, 6.25793014e-01, 6.74873717e-01, 6.81096693e-01,
        7.00866674e-01, 7.29266443e-01],
       ...,
       [0.00000000e+00, 7.01124868e-01, 7.56172775e-01, 7.65772271e-01,
        7.67272509e-01, 7.86414694e-01],
       [0.00000000e+00, 3.21278145e-01, 4.53158502e-01, 5.00656107e-01,
        5.52467649e-01, 5.86329848e-01],
       [0.00000000e+00, 5.37557063e-01, 5.71062098e-01, 6.07051309e-01,
        6.18090540e-01, 6.28401892e-01]])

In [ ]:
distances.shape

(746, 6)

In [ ]:
indices

array([[  0, 578,  54, 528, 671, 557],
       [  1, 397,  45,   2, 656, 425],
       [  2, 213, 612, 704, 610, 208],
       ...,
       [743, 407, 389, 337, 579, 497],
       [744, 204, 442, 299, 494, 184],
       [745, 234, 410,  98, 266, 188]])

In [ ]:
indices.shape

(746, 6)

In [ ]:
df_title = pd.DataFrame(us_canada_user_rating_pivot.index.ravel(), columns=['Title'])

In [ ]:
dict_title = df_title.T.to_dict('index')['Title']
dict_title

{0: '1984',
 1: '1st to Die: A Novel',
 2: '2nd Chance',
 3: '4 Blondes',
 4: '84 Charing Cross Road',
 5: 'A Bend in the Road',
 6: 'A Case of Need',
 7: 'A Child Called \\It\\": One Child\'s Courage to Survive"',
 8: 'A Civil Action',
 9: 'A Cry In The Night',
 10: 'A Darkness More Than Night',
 11: 'A Day Late and a Dollar Short',
 12: 'A Fine Balance',
 13: 'A Great Deliverance',
 14: 'A Heartbreaking Work of Staggering Genius',
 15: 'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))',
 16: 'A Lesson Before Dying (Vintage Contemporaries (Paperback))',
 17: 'A Man Named Dave: A Story of Triumph and Forgiveness',
 18: 'A Man in Full',
 19: 'A Map of the World',
 20: 'A Painted House',
 21: 'A Patchwork Planet',
 22: 'A Prayer for Owen Meany',
 23: 'A Thin Dark Line (Mysteries &amp; Horror)',
 24: "A Thousand Acres (Ballantine Reader's Circle)",
 25: 'A Time to Kill',
 26: "A Virtuous Woman (Oprah's Book Club (Paperback))",
 27: 'A Walk to Remember',
 28: 'A Widow for One Year',


In [ ]:
df_indices = pd.DataFrame(indices, columns=['n1','n2','n3','n4','n5','n6'])

In [ ]:
df_indices_map = df_indices.apply( lambda x : x.map(dict_title))

In [ ]:
df_title_indices = pd.concat([df_title,df_indices_map],axis='columns')

In [ ]:
df_title_indices

Title  ...                                                 n6
0                                                 1984  ...  The Fellowship of the Ring (The Lord of the Ri...
1                                  1st to Die: A Novel  ...                  Roses Are Red (Alex Cross Novels)
2                                           2nd Chance  ...                                    Flesh and Blood
3                                            4 Blondes  ...                                      Here on Earth
4                                84 Charing Cross Road  ...      The Amazing Adventures of Kavalier &amp; Clay
..                                                 ...  ...                                                ...
741                                    Year of Wonders  ...                                  Midwives: A Novel
742                                   You Belong To Me  ...                         Let Me Call You Sweetheart
743  Zen and the Art of Motorcycle Maintenance: An ...  ...                                 That Camden Summer
744                                               Zoya  ...                                          Exclusive
745                                \O\" Is for Outlaw"  ...  F Is for Fugitive (Kinsey Millhone Mysteries (...

[746 rows x 7 columns]